src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_of_depenents__c</fullName>
        <label>No. of dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_cars__c</fullName>
        <label>Number of cars</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AffordabilityResults__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>AffordabilityResults</relationshipLabel>
        <relationshipName>AffordabilityResults</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StressedHPPRepayment__c</fullName>
        <inlineHelpText>HPP Monthly repayment stressed at 2%</inlineHelpText>
        <label>StressedHPPRepayment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>AffordabilityResults</label>
    <nameField>
        <displayFormat>AFR{0000}</displayFormat>
        <label>AffordabilityResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AffordabilityResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prospect_Customer__c</fullName>
        <label>Prospect/Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_Planner_Item__c.object
<CustomObject>
    <description>Each record represents an expense/bill for either an account or an application(opportunity).</description>
    <fields>
        <fullName>Account_Value__c</fullName>
        <label>Account Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant_Total__c</fullName>
        <label>Applicant Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BDM_Comments__c</fullName>
        <label>BDM Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BudgetPlannerConfig__c</fullName>
        <label>BudgetPlannerConfig</label>
        <referenceTo>BudgetPlannerConfig__c</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Value__c</fullName>
        <label>Credit Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>BudgetPlannerConfig__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_to_be_used__c</fullName>
        <label>Value to be used</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Budget Planner Item</label>
    <nameField>
        <label>BudgetPlannerAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Planner Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetPlannerConfig__c.object
<CustomObject>
    <description>Object to store the system wide configuration data for the budget planner.
Each record represents a type of bill or expense.  Different minimum values can be entered depending on the type of application and number of applicants.

This object also controls the fields which appear on the application screen, as well as the application form.</description>
    <fields>
        <fullName>Car_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Car Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsStressed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsStressed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Joint_App_1_Dep__c</fullName>
        <label>Joint App 1 Dep</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App_2_Dep__c</fullName>
        <label>Joint App 2 Dep</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App_3_Dep__c</fullName>
        <label>Joint App 3 Dep</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App__c</fullName>
        <label>Joint App</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SingleApp__c</fullName>
        <label>SingleApp</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BudgetPlannerConfig</label>
    <nameField>
        <label>BudgetPlannerConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BudgetPlannerConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IBB_Product_Type__c</fullName>
        <formula>TEXT( IBB_Product__r.Type_of_Product__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HPPUnderwrittingBudgetHelper.cls
public class HPPUnderwrittingBudgetHelper
{
    public List<HPPUnderwrittingBudgetData> Items{get;set;}     
    private Integer NoDependants{get;set;}
    private Integer NoApplicants{get;set;}
    private Integer NoCars{get;set;}
    
   
      
    
    public void Load(String oppId, Integer NoCars,String budgetToUse)
    {
        
        List<Applicant__c> Accounts = [select Prospect_Customer__r.No_of_depenents__c,Prospect_Customer__r.number_of_cars__c
                                     from applicant__c
                                    where Opportunity__c =: oppId ];
        NoApplicants = Accounts.Size();
        NoDependants = 0;

		
		// C0597 HPP-BTL Start
		Boolean isBTL = false;
		Opportunity oppo = [select IBB_Product_Type__c from Opportunity where ID=:oppId limit 1];
		if ( oppo.IBB_Product_Type__c == 'BTL Purchase Plan' || oppo.IBB_Product_Type__c == 'BTL Purchase Plan Scotland' || oppo.IBB_Product_Type__c == 'Buy To Let Purchase Plan Scotland' || oppo.IBB_Product_Type__c == 'Buy To Let Purchase Plan' )
		{
			isBTL = true;
		}
		// C0597 HPP-BTL Start
        
        for(Applicant__c a: Accounts)
        {
            if(a.Prospect_Customer__r.No_of_depenents__c != null)
            {
                NoDependants += a.Prospect_Customer__r.No_of_depenents__c.intValue();
            }  
        }
        
        
        if(budgetToUse == null)
            budgetToUse = MiniumText();
        
        
        if(NoCars == null || NoCars < 1)
            NoCars = 1;
       
        
        
     
        
        List<Budget_Planner_Item__c> BudgetItems = [select name,Credit_Value__c , bdm_comments__c,Account_Value__c, opportunity__c,Applicant_Total__c, account__c, id, display_name__c, budgetplannerconfig__c,budgetplannerconfig__r.name,
                                     budgetplannerconfig__r.SingleApp__c, budgetplannerconfig__r.Joint_App__c,
                                     budgetplannerconfig__r.Joint_App_1_Dep__c, budgetplannerconfig__r.Joint_App_2_Dep__c,
                                     budgetplannerconfig__r.Joint_App_3_Dep__c, budgetplannerconfig__r.car_bill__c,
                                     budgetplannerconfig__r.IsStressed__c,Value_to_be_used__c
                         from budget_planner_item__c 
                        where opportunity__c =:oppId order by  budgetplannerconfig__r.order__c ];
         
          
                 
        Items = new List<HPPUnderwrittingBudgetData>();
                                             
        for(Budget_Planner_Item__c item : BudgetItems)
        {
            HPPUnderwrittingBudgetData data = new HPPUnderwrittingBudgetData();
            data.Item = item;
            data.Minimum = Minimum(item,budgetToUse  );
            if(data.Minimum == null)
                data.Minimum = 0;
                
                
                
            if(item.budgetplannerconfig__r.Car_Bill__c)
            {
                system.debug('car Bill ' + item.display_name__c + ' ' + NoCars);
                data.Minimum = data.Minimum  * NoCars;
            }
            
            if(data.item.Applicant_Total__c == null)
                data.item.Applicant_Total__c = 0;
            
            Decimal min = data.Minimum * 0.75; 
            
            if(data.item.Applicant_Total__c < min && data.Minimum > 0 )
            {
                data.FigureUsed = data.Minimum;
            }
            else
            {
                data.FigureUsed = data.item.Applicant_Total__c;
            } 
            
            
            
            if(item.budgetplannerconfig__r.IsStressed__c && !isBTL) // C0597 HPP-BTL Do Not update HPP BP item with StressedHPPPayment result
            {
                List<AffordabilityResults__c> ar = [select StressedHPPRepayment__c 
                                                from AffordabilityResults__c 
                                                where Opportunity__c =:oppid 
                                                order by createddate desc limit 1
                                                 ];
                if(ar.size() > 0)
                {                                 
                    data.FigureUsed = ar[0].StressedHPPRepayment__c ;
                    data.Minimum = ar[0].StressedHPPRepayment__c ;
                    data.item.Applicant_Total__c = ar[0].StressedHPPRepayment__c ;
                }
            }
            
            
            Items.add(data);           
        }                                                                               
    }
    
    
    public static String MinimumText(Integer NoApplicants, Integer NoDependants)
    {
         if(NoApplicants == 1)
            return 'Single App';
            
        if(NoDependants == 0)
            return 'Joint App';
            
        if(NoDependants == 1)
            return 'Joint App + 1 dependent';
            
        if(NoDependants == 2)
            return 'Joint App + 2 dependent';
            
        if(NoDependants > 2)
            return 'Joint App 3 or more dependents';                        
        return 'Single App';   
    }
    
    public String MiniumText()
    {
        return MinimumText(NoApplicants ,NoDependants );
    
    /*
        if(NoApplicants == 1)
            return 'Single App';
            
        if(NoDependants == 0)
            return 'Joint App';
            
        if(NoDependants == 1)
            return 'Joint App + 1 dependent';
            
        if(NoDependants == 2)
            return 'Joint App + 2 dependent';
            
        if(NoDependants > 2)
            return 'Joint App 3 or more dependents';                        
        return 'Single App';  
        */ 
    
    }
    
    public Decimal Minimum(Budget_Planner_Item__c item, String budgetToUse)
    {
        if(budgetToUse== 'Single App')
            return item.budgetplannerconfig__r.SingleApp__c;
            
        if(budgetToUse== 'Joint App')
            return item.budgetplannerconfig__r.Joint_App__c;
            
        if(budgetToUse== 'Joint App + 1 dependent')
            return item.budgetplannerconfig__r.Joint_App_1_Dep__c;
            
        if(budgetToUse== 'Joint App + 2 dependent')
            return item.budgetplannerconfig__r.Joint_App_2_Dep__c;
            
        if(budgetToUse== 'Joint App 3 or more dependents')
            return item.budgetplannerconfig__r.Joint_App_3_Dep__c;                        
        return 0;    
    }
    
    
}