src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Net_Monthly_Income__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Net Monthly Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>No_of_depenents__c</fullName>
        <label>No. of dependents</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_cars__c</fullName>
        <label>Number of cars</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BudgetPlannerConfig__c.object
<CustomObject>
    <description>Object to store the system wide configuration data for the budget planner.
Each record represents a type of bill or expense.  Different minimum values can be entered depending on the type of application and number of applicants.

This object also controls the fields which appear on the application screen, as well as the application form.</description>
    <fields>
        <fullName>Car_Bill__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Car Bill</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Joint_App_1_Dep_ONS__c</fullName>
        <label>Joint App 1 Dep ONS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App_2_Dep_ONS__c</fullName>
        <label>Joint App 2 Dep ONS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App_3_Dep_ONS__c</fullName>
        <label>Joint App 3 Dep ONS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joint_App_ONS__c</fullName>
        <label>Joint App ONS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SingleApp_ONS__c</fullName>
        <label>SingleApp ONS</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BudgetPlannerConfig</label>
    <nameField>
        <label>BudgetPlannerConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BudgetPlannerConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IBB_Product_Set__c.object
<CustomObject>
    <fields>
        <fullName>Conga_AIP_MMR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For MMR doc</description>
        <label>DocuGen AIP MMR</label>
        <referenceTo>CongaSettings__c</referenceTo>
        <relationshipLabel>Product Sets (Conga AIP MMR)</relationshipLabel>
        <relationshipName>IBB_Product_Sets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>Buy to let</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Set</label>
    <nameField>
        <label>Product Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sets</pluralLabel>
    <recordTypes>
        <fullName>HPP</fullName>
        <active>true</active>
        <description>For use with HPP eligibility</description>
        <label>HPP</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Attachment_Welcome_Letter__c</fullName>
        <label>Attachment Welcome Letter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear_Customer__c</fullName>
        <label>Dear Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance_Required__c</fullName>
        <label>Finance Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Assisted_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Income Assisted Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Buy To Let Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>BTL Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Home Purchase Plan Premier</fullName>
                </value>
                <value>
                    <fullName>Long Term Savings</fullName>
                </value>
                <value>
                    <fullName>Short Term Savings</fullName>
                </value>
                <value>
                    <fullName>Current Account</fullName>
                </value>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>Personal Finance</fullName>
                </value>
                <value>
                    <fullName>Commercial Property Finance</fullName>
                </value>
                <value>
                    <fullName>HPP BTL (future)</fullName>
                </value>
                <value>
                    <fullName>Premier Banking</fullName>
                </value>
                <value>
                    <fullName>IFA/Wealth Management</fullName>
                </value>
                <value>
                    <fullName>Discretionary Portfolio Service (DPS)</fullName>
                </value>
                <value>
                    <fullName>HPP Premier</fullName>
                </value>
                <value>
                    <fullName>HPP Buy-to-Let (BTL)</fullName>
                </value>
                <value>
                    <fullName>HPP Buy To Let (Rent Only)</fullName>
                </value>
                <value>
                    <fullName>Home Purchase Scotland</fullName>
                </value>
                <value>
                    <fullName>Buy To Let Purchase Plan Scotland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Joint_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Joint Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_of_Finance__c</fullName>
        <label>Term of Finance</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MMR_AIP_Controller.cls
public class MMR_AIP_Controller extends MMR_PageControllerBase
{
    public List<Account> Accs{get;set;}
    public Opportunity Opp{get;set;}
    public Boolean PassedAffordability{get;set;}
    public Boolean DocumentCreated{get;set;}
    public String FileId {get;set;}
    
    public Transient Interfaces.ICongaSettings m_congaSettings;    
    public MMR_AIP_Controller ()
    {
         
    }    
    
    public PageReference Setup()
    {
        
        String oppSoql = LiabilitiesHelperFunctions.SoqlQuery('MMR_AIP_Opp') + ' from Opportunity where id= \'' + opportunityId + '\'';
        system.debug('OPP soql :' + oppSoql);
        List<Opportunity > Opps = DataBase.Query(oppSoql);
        if(Opps.size() != 1)
            return null;
            
        Opp = Opps[0];  
        
        Accs = new List<Account>();
        for(String accid : lstAccountIds )
        {
            String soql = LiabilitiesHelperFunctions.SoqlQuery('MMR_AIP_Applicant') + ' from account where id = \'' + accid + '\''  ;
            Account a = DataBase.Query(soql);
            Accs.add(a);
        }
        
        UpdateDearField();
        return null;
    }   
    
    
    private void UpdateDearField()
    {
        String dear = 'Dear ';
        
        boolean first = true;
        
        for(Account a : accs)
        {
            if(first)
            {
                dear += a.Salutation+ ' ' + a.lastname;
                first = false;
                continue;
            }
        
            dear += ' and ' +  a.Salutation+ ' ' + a.lastname;
        }
        dear += ',';
        
        Opp.Dear_customer__c = dear; 
        update opp;        
    }

   
    public PageReference Save()
    {
        try
        {
        //update num btl and num properties
        
        update Accs;
        
        }
        catch(Exception ex)
        {
        
        }
        return null;
    }
    
    public PageReference Complete()
    {
        try {
          update accs;
          update Opp;
        }
        catch (Exception ex) {
          System.debug('Exception on Update exOpp : ' + ex);
          return null;
        }
    
        CompleteEvent();
        return GoToNextEvent();
  
    }
    
    private Decimal GetValue(BudgetPlannerConfig__c c,Integer depend)
    {
        if(Accs.size()==1 && !Opp.Is_Joint_Application__c)
            return c.SingleApp_ONS__c;
            
        if(depend == 0)
            return c.Joint_App_ONS__c;
            
        if(depend == 1)
            return c.Joint_App_1_Dep_ONS__c;
            
        if(depend == 2)
            return c.Joint_App_2_Dep_ONS__c;
            
        if(depend > 2)
            return c.Joint_App_3_Dep_ONS__c;
            
        
        return 0;    
    }
    
    public Decimal Diff {get;set;}
    public Decimal hppRepayment {get;set;}
    public Decimal total{get;set;}
    
    public PageReference Afford()
    {
        update opp;
        update accs;
    
        /*Integer noCars=0;
        Integer noDepend=0;
        Decimal netIncome = 0;
        
        for(Account a : Accs)
        {
            noCars += integer.valueof(a.Number_of_cars__c);
            noDepend += integer.valueof(a.No_of_depenents__c);
            netIncome += a.Net_Monthly_Income__c;
        }
        
        List<BudgetPlannerConfig__c> configs = [select id,SingleApp_ONS__c,Joint_App_ONS__c, Joint_App_1_Dep_ONS__c,Joint_App_2_Dep_ONS__c,Joint_App_3_Dep_ONS__c,Car_Bill__c from BudgetPlannerConfig__c ];
        
        total = 0;
        
        for(BudgetPlannerConfig__c c : configs )
        {
            Decimal figure=GetValue(c,noDepend); 
            if(figure == null)
                figure = 0;          
            if(c.Car_Bill__c)
            {
                figure = figure * noCars;
            }
            total += figure;            
        }
        
        //hpp payment
        Double principle = opp.Finance_Required__c;
        Double interest = 5.49;//benchmarkRate;
        Double length = opp.Term_of_Finance__c;
        Double monthlyInterest = interest / (12 * 100);
        Double numberOfMonthsAmortized = length * 12;
        
        hppRepayment = principle * (monthlyInterest / (1 - Math.pow((1 + monthlyInterest), -numberOfMonthsAmortized)));
        hppRepayment = hppRepayment.round();*/
        
        
        try{
            if ( opp.Interested_in__c.equalsIgnoreCase('Buy To Let Purchase Plan' ) || opp.Interested_in__c.equalsIgnoreCase('Buy To Let Purchase Plan Scotland' ) ){
                List<double> btlAffordResult=LiabilitiesHelperFunctions.btlAfford(opp,accs);
                
                double netIncome=btlAffordResult[2];
                hppRepayment=btlAffordResult[0];
                total=btlAffordResult[1];
                
                system.debug('response:'+btlAffordResult);
                
                diff=netIncome-total;
                
                /*double netIncome=1000;
                hppRepayment=300;
                total=500;
                diff=netIncome-total;*/
				/* C0586 */
                //passedAffordability=diff >= 0;
				System.debug ( 'This is Inc flag ' + Opp.Income_Assisted_Application__c );
				if ( diff >= 0 || Opp.Income_Assisted_Application__c == true )
				{
					passedAffordability = true;
				}
				else
				{
					passedAffordability = false;
				}
            }
            else{
                List<double> hppAffordResult=LiabilitiesHelperFunctions.hppAfford(opp,accs);
                
        
                double netIncome=hppAffordResult[2];
                hppRepayment=hppAffordResult[0];
                total=hppAffordResult[1];
                
                decimal t = total + hppRepayment;
                diff = netIncome - t;
                
                PassedAffordability = diff > 0;
            }
        }
        catch(Exception e){
            List<double> hppAffordResult=LiabilitiesHelperFunctions.hppAfford(opp,accs);
                
        
            double netIncome=hppAffordResult[2];
            hppRepayment=hppAffordResult[0];
            total=hppAffordResult[1];
            
            decimal t = total + hppRepayment;
            diff = netIncome - t;
            
            PassedAffordability = diff > 0;
        }
        
        
        
        system.debug('inside Afford(), hppRepayment:'+hppRepayment);
        
        return null;
    }
    
    public PageReference CreateDoc()
    {
        system.debug('OPP id:' + opportunityId );
        
        if(m_congaSettings == null)
        {
            IBB_Product_Set__C ps = [select Conga_AIP_MMR__c from IBB_Product_Set__C where id=:Prodset.id];
            m_congaSettings = new CongaSettings(ps.Conga_AIP_MMR__c);
        }
        
        
        string body= m_congaSettings.CallConga(opportunityId);   
        
        if(m_congaSettings.GetAttachmentId() != null)
        {
            FileId =  m_congaSettings.GetAttachmentId();
            //opp.Attachment_Welcome_Letter__c= m_congaSettings.GetAttachmentId();
            DocumentCreated = true;
            update opp;
        }      

        return null;
    }
    
    
    public PageReference Prev()
    {
        return new PageReference('/apex/mmr_aip_applicants?id=' + eventid);
    }
       
    public List<SelectOption> getTitles() {
            List<SelectOption> options = new List<SelectOption>();
             options.add(new SelectOption('Mr','Mr'));
            options.add(new SelectOption('Mrs','Mrs'));
            options.add(new SelectOption('Miss','Miss'));
            options.add(new SelectOption('Ms','Ms'));
            options.add(new SelectOption('Dr','Dr'));            
            options.add(new SelectOption('Other','Other'));
             options.add(new SelectOption('Prof','Prof'));
              options.add(new SelectOption('Sheikh','Sheikh'));
            return options;
    }
}