src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prospect_Customer__c</fullName>
        <label>Prospect/Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_Planner_Item__c.object
<CustomObject>
    <description>Each record represents an expense/bill for either an account or an application(opportunity).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant_Total__c</fullName>
        <label>Applicant Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BudgetPlannerConfig__c</fullName>
        <label>BudgetPlannerConfig</label>
        <referenceTo>BudgetPlannerConfig__c</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>BudgetPlannerConfig__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Budget Planner Items</relationshipLabel>
        <relationshipName>Budget_Planner_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_to_be_used__c</fullName>
        <label>Value to be used</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Budget Planner Item</label>
    <nameField>
        <label>BudgetPlannerAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Planner Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BudgetPlannerConfig__c.object
<CustomObject>
    <description>Object to store the system wide configuration data for the budget planner.
Each record represents a type of bill or expense.  Different minimum values can be entered depending on the type of application and number of applicants.

This object also controls the fields which appear on the application screen, as well as the application form.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BudgetPlannerConfig</label>
    <nameField>
        <label>BudgetPlannerConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BudgetPlannerConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MMR_HPPBudgetPlannerHelper.cls
public class MMR_HPPBudgetPlannerHelper
{
    private String m_oppId;
    public MMR_HPPBudgetPlannerHelper(String oppId)
    {
        m_oppId = oppId;
    }
    
    /*
    public void ReCalculateTotals()
    {
        /*
         List<Budget_Planner_Item__c>    BudgetItems = [select name, opportunity__c, account__c, id, display_name__c, budgetplannerconfig__c,budgetplannerconfig__r.name
                         from budget_planner_item__c 
                        where account__c in (select Prospect_Customer__c 
                                             from Applicant__c 
                                             where opportunity__c=:m_oppId ) ];
                                             
        ReCalculateTotals(BudgetItems );
    }
    */
    
    public void ReCalculateTotals()
    {
    
    
        List<Budget_Planner_Item__c> CombinedBudgetItems = [select name, opportunity__c, account__c, id, display_name__c, budgetplannerconfig__c,budgetplannerconfig__r.name
                         from budget_planner_item__c 
                        where opportunity__c =:m_oppId ];
                        
                        
                        
        List<BudgetPlannerConfig__c> config = [select id, name from BudgetPlannerConfig__c order by order__c ];

        system.debug('Item Count : ' + config.size());

        for(BudgetPlannerConfig__c c : config)
        {
            budget_planner_item__c found;
            for(Budget_Planner_item__c item: CombinedBudgetItems )
            {
                if(item.budgetPlannerConfig__c == c.id)
                {
                    system.debug('Found item : ' + item.name );
                    found = item;
                    break;
                }
            }
            
            //create item if it does not exist against the opportunity
            if(found == null)
            {
                system.debug('New Item ' + c.name);
                found = new budget_planner_item__c();
                found.opportunity__c = m_oppId ;
                found.budgetplannerconfig__c = c.id;
                CombinedBudgetItems.add(found);
            }
        }
        //Integer i = 1/0;
        upsert CombinedBudgetItems; 
    }

	// C0586 Start
	public void SaveIncomeAssistedBTLDeficit(double Deficit)
	{
		System.debug('IAA BTL Deficit:'+Deficit);
		List<BudgetPlannerConfig__c> config = [select id, name from BudgetPlannerConfig__c where name = 'Income Assisted BTL Deficit' ];
		Id BPConfigID;
		for(BudgetPlannerConfig__c	c: config)
		{
			BPConfigID = c.Id;
			System.debug('BTL IAA Config ID:'+c.Id+' - Name:'+c.Name);
		}	
		List<Budget_Planner_Item__c> budgetItems = [select name, opportunity__c, account__c, id, display_name__c, budgetplannerconfig__c,budgetplannerconfig__r.name
                         from budget_planner_item__c 
                        where opportunity__c =:m_oppId and budgetplannerconfig__r.id=:BPConfigID ];
		for(Budget_Planner_Item__c i: budgetItems)
		{
			System.debug('Item ID:'+i.Id);
			i.Value_to_be_used__c = Deficit;
			i.Applicant_Total__c = Deficit;
		}
		upsert budgetItems;
		//Integer i = 1/0;
		
	}

	public Decimal GetBTLBasicBudgetPlannerCosts() // C0586 - UW changes
	{
		// Gets the values of 'Service Charge', "Maintenance Charge', and 'Ground Rent' from the Budget Planner and returns the total
		
		Decimal BTLBasicBudgetPlannerCosts = 0;
		List<BudgetPlannerConfig__c> config = [select id, name from BudgetPlannerConfig__c where name in ('Ground Rent','Service Charge','Maintenance Charge') ];

		List<Budget_Planner_Item__c> budgetItems = [select name, opportunity__c, account__c, id, display_name__c, budgetplannerconfig__c,budgetplannerconfig__r.name,Value_to_be_used__c
                         from budget_planner_item__c 
                        where opportunity__c =:m_oppId];

		for(BudgetPlannerConfig__c	c: config)
		{
			for(Budget_Planner_Item__c i: budgetItems)
			{
				if(i.BudgetPlannerConfig__c==c.Id)
				{
					BTLBasicBudgetPlannerCosts+= i.Value_to_be_used__c; // Or i.Applicant_Total__c
				}
			}
		}	
		
		//Integer i = 1/0;
		return BTLBasicBudgetPlannerCosts;
	
		
	}
	// C0586 End

}