src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prospect_Customer__c</fullName>
        <label>Prospect/Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Roles__c</fullName>
        <label>Allowed Roles</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CustomPageLocation__c</fullName>
        <label>CustomPageLocation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequiredFields__c</fullName>
        <label>RequiredFields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <fields>
        <fullName>EventStatus__c</fullName>
        <label>EventStatus</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <label>EventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HPP_extended_opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>HPP extended opportunities</relationshipLabel>
        <relationshipName>HPP_extended_opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HPP extended opportunity</label>
    <nameField>
        <displayFormat>HPPEO{0000}</displayFormat>
        <label>HPP extended opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HPP extended opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IBB_Product__c.object
<CustomObject>
    <fields>
        <fullName>IBB_Product_Set__c</fullName>
        <label>IBB Product Set</label>
        <referenceTo>IBB_Product_Set__c</referenceTo>
        <relationshipName>IBB_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IDD_Document__c</fullName>
        <label>IDD Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductEventDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductEventDirector</label>
        <referenceTo>ProductEventDirector__c</referenceTo>
        <relationshipLabel>Products (ProductEventDirector)</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IBB_Product_Set__c.object
<CustomObject>
    <fields>
        <fullName>Conga_AIP_Letter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DocuGen AIP Letter</label>
        <referenceTo>CongaSettings__c</referenceTo>
        <relationshipLabel>Product Sets (Conga AIP Letter)</relationshipLabel>
        <relationshipName>IBB_Product_Sets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conga_Application_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DocuGen Application Form</label>
        <referenceTo>CongaSettings__c</referenceTo>
        <relationshipLabel>Product Sets (Conga Application Form)</relationshipLabel>
        <relationshipName>IBB_Product_Sets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conga_Welcome_Letter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DocuGen Welcome Letter</label>
        <referenceTo>CongaSettings__c</referenceTo>
        <relationshipLabel>Product Sets (Conga Welcome Letter)</relationshipLabel>
        <relationshipName>IBB_Product_Sets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IDD_Document__c</fullName>
        <label>IDD Document</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>Buy to let</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_No_of_Applicants__c</fullName>
        <label>Max No of Applicants</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductSetType__c</fullName>
        <label>Product Set Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>HPS</fullName>
                </value>
                <value>
                    <fullName>BTL</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>HTB</fullName>
                </value>
                <value>
                    <fullName>CDM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Set</label>
    <nameField>
        <label>Product Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sets</pluralLabel>
    <recordTypes>
        <fullName>HPP</fullName>
        <active>true</active>
        <description>For use with HPP eligibility</description>
        <label>HPP</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HPP_extended_opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HPP extended opportunity</label>
        <referenceTo>HPP_extended_opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IBB_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>IBB_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Buy To Let Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>BTL Purchase Plan</fullName>
                </value>
                <value>
                    <fullName>Home Purchase Plan Premier</fullName>
                </value>
                <value>
                    <fullName>Long Term Savings</fullName>
                </value>
                <value>
                    <fullName>Short Term Savings</fullName>
                </value>
                <value>
                    <fullName>Current Account</fullName>
                </value>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>Personal Finance</fullName>
                </value>
                <value>
                    <fullName>Commercial Property Finance</fullName>
                </value>
                <value>
                    <fullName>HPP BTL (future)</fullName>
                </value>
                <value>
                    <fullName>Premier Banking</fullName>
                </value>
                <value>
                    <fullName>IFA/Wealth Management</fullName>
                </value>
                <value>
                    <fullName>Discretionary Portfolio Service (DPS)</fullName>
                </value>
                <value>
                    <fullName>HPP Premier</fullName>
                </value>
                <value>
                    <fullName>HPP Buy-to-Let (BTL)</fullName>
                </value>
                <value>
                    <fullName>HPP Buy To Let (Rent Only)</fullName>
                </value>
                <value>
                    <fullName>Home Purchase Scotland</fullName>
                </value>
                <value>
                    <fullName>Buy To Let Purchase Plan Scotland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_People_Applying__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of People Applying</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductEventDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductEventDirector</label>
        <referenceTo>ProductEventDirector__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProductSwitching</fullName>
        <active>true</active>
        <businessProcess>HPP CAA</businessProcess>
        <description>For use only with product switching system</description>
        <label>ProductSwitching</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProductEventDirector__c.object
<CustomObject>
    <fields>
        <fullName>BaseController__c</fullName>
        <label>BaseController</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HPP</fullName>
                </value>
                <value>
                    <fullName>BAA</fullName>
                </value>
                <value>
                    <fullName>MMR</fullName>
                </value>
                <value>
                    <fullName>CAA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>ProductEventDirector</relationshipLabel>
        <relationshipName>ProductEventDirector</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductEventDirector</label>
    <nameField>
        <label>ProductEventDirector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductEventDirector</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SOQLQuery__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SOQLQuery</label>
</CustomObject>

src/classes/HPPBaseEventController.cls
public virtual class HPPBaseEventController{
    private static aLog.Logger Log = new aLog.Logger('HPPBaseEventController');
    public String eventId 
    {
        get 
        {
            if (eventId == null)
            {
                eventId = ApexPages.currentPage().getParameters().get('id');
            }
            return eventId ;
        }
        set;
    }
    
    public String oppId
    {
        get 
        {
            if (oppId== null)
            {
                oppId= ApexPages.currentPage().getParameters().get('oppId');
            }
            return oppId;
        }
        set;
    }    
    
    public Boolean ProductSwitch
    {
        get{
            return Opp.recordtype.developername.equalsIgnoreCase('ProductSwitching');            
        }
    }
    
    public String opportunityId{get;set;}    
    public I_IBBEvents director {get;set;}
    public Integer CurApp{get;set;}
    public HPPBaseEventHelper.EventType TypeofEvent{get;set;}
    
    public HPP_extended_opportunity__c exOpp
    {
        get{
            if(exOpp == null)
            {
                exOpp = DataHelper.GetHPPExtendedOpportunityByOpp(string.valueof(opportunityId))[0];
            }
            return exOpp;
        }
        set;
        
    }
    public IBB_Product__c Prod {get;set;}  
    public List<Account> Accounts {get;set;}  
    public List<Applicant__c> Applicants {get;set;}
        
    public EventLog__c EventLog{get;set;}
    public Event__c Event{get;set;}   
    
    public Opportunity Opp
    {
        get{
            return BaseOpportunity;
        }
        set{
            BaseOpportunity = value;
        }
    }
    
    
    public Opportunity BaseOpportunity{get;set;}
     
    public boolean IsCompleted{get;set;}
    public IBB_Product_set__c prodSet{get;set;}  
    public String NextEventUrl {get;set;}  
    
    /*private Boolean UserAuthorised()
    {
        User u = [select UserRoleId from user where id=: UserInfo.getUserId()];
        
        if(Event.Allowed_Roles__c == null)
            return true;
        
         List<String> roleIds= 
              (List<String>)JSON.deserialize(Event.Allowed_Roles__c, List<String>.class);
        
        if(roleIds.size() == 0)
            return true;
        
        //Get event roles 
        List<UserRole> userRoles = [select id from userrole where id in: roleIds];
        
        for(UserRole ur : userRoles)
        {
            if(ur.id == u.UserRoleId)
                return true;
        }
        return false;
    }
    */

    public Boolean IsUserAuthorised
    {
        get{
            return HPPBaseEventHelper.UserAuthorised(Event);
        }
    }    
    
    public PageReference CorrectPage(String page)
    {
        if(!ISCorrectPage(page))
        {
            return new PageReference(event.CustomPageLocation__c + '?id=' + EventLog.id);
        }
        
        if(!IsUserAuthorised)
            return new PageReference('/apex/eventsecurity' + '?id=' + EventLog.id);
        
        return null;
    }

    public Boolean IsCorrectPage(String page)
    {
        system.debug('Checking Page :' + page);
            //check page is the correct page
          
 
            
            if(Event.CustomPageLocation__c != null & page==null)
                return false;
            
            if(Event.CustomPageLocation__c != null & page!= null)
            {
                String currentPage = '/apex/' + page;
                system.debug('C: ' + currentPage + ' , P: ' + page);
                
                return currentPage.equalsIgnoreCase(Event.CustomPageLocation__c);                 
            }
            return false;
    }

    public Account Acc
    {
        get
        {           
            if(Accounts.Size() == 0) return null;
            
            if(Accounts.size() < Curapp)
            {
                Curapp = Accounts.size();                
            }
            
            return Accounts[CurApp-1];
        }
    }
    
    private void LoadEvent()
    {
        IsCompleted = false;
        List<EventLog__c> listEvent = DataHelper.GetEventLog(eventId );
        if(listEvent.size() == 0)
        return;
        
        EventLog = listEvent[0];        
        Event = DataHelper.GetEvent(EventLog.Event__r.id)[0];
        if(EventLog.eventstatus__c != 'Open')
        {
            IsCompleted = true;         
        }  
    }  
    
    public ProductEventDirector__c oDirector{get;set;}
    
    public HPPBaseEventController() 
    {    
        //If an eventid is passed, get the opportunity from the event.  Otherwise look for the opportunity id in the querystring
        //String opportunityId;
        

        Accounts = new List<Account>();
        if(eventId == null)
        {   
            if(oppId == null)
                return;     
            opportunityId = oppId;                       
        }    
        else
        {
            LoadEvent();
            if(EventLog == null)
                return;              
                
            opportunityId= EventLog .Opportunity__c;
        }
        
        Logger.debug('OPP id : ' + opportunityId);
               
        opportunity oo = [select id,ProductEventDirector__c from opportunity where id=:opportunityId ];
        director = new IBBEvents(oo.ProductEventDirector__c);        
        oDirector = DataHelper.GetDirector(oo.ProductEventDirector__c)[0];
        
        TypeofEvent = HPPBaseEventHelper.GetEventType(oDirector.BaseController__c);       
                     
        BaseOpportunity = HPPBaseEventHelper.LoadOpportunity(TypeofEvent,opportunityId) ;//   DataHelper.GetOpportunity(opportunityId)[0];
        
        system.debug(BaseOpportunity);
        
        
        
        
        //Load product     
        system.debug('load product : ' + opp.IBB_Product__c);
        if(opp.IBB_Product__c != null)
        {
        prod = DataHelper.GetProduct(opp.IBB_Product__c)[0];          
        }
        
        if(TypeofEvent == HPPBaseEventHelper.EventType.HPP)        
        prodSet = [select Conga_Welcome_Letter__c, Max_No_of_Applicants__c, ProductSetType__c, IDD_Document__c,name,Conga_Application_Form__c,Conga_AIP_Letter__c  from IBB_Product_Set__c where name=: opp.interested_in__c limit 1 ];
        
        //if(TypeofEvent == EventType.MMR || TypeofEvent == EventType.BAA)
        
        
        

        //String oppid=Opp.id;

        Applicants = DataHelper.GetApplicants(Opp.Id);
        
        for(Integer i = 0; i< Applicants.Size();i++)
        {       
                Account applicant = DataHelper.GetAccount(Applicants [i].Prospect_Customer__c)[0];
                Applicants[i].Prospect_Customer__r = applicant;
                Accounts.add(applicant);

        }
        opp.Number_of_People_Applying__c  = Accounts.size();
        CurApp = 1;
    }
    
    public List<SelectOption> getNumApplicants() 
    {    
        List<SelectOption> options = new List<SelectOption>();               
        for(Integer i =0; i<prodSet.Max_No_of_Applicants__c; i++)
        {
               options.add(new SelectOption(string.valueof(i+1),string.valueof(i+1)));    
        }
        return options;
    }  
    
        public RecordType recType {
        get {
            if (recType == null){            
                recType = [select id from recordType where ispersontype=true and sobjectType='account' and DeveloperName = 'ProspectCustomer' limit 1];
            }
            return recType;
        }
        set;
    }  
    
    public EventLog__c CreatedEvent {get;set;}
    
    
    public boolean IsCredit
    {
        get 
        {
            if (IsCredit== null)
            {
                String b= ApexPages.currentPage().getParameters().get('credit');
                if(b == null) IsCredit = false;     
                
                try
                {
                    IsCredit = boolean.valueof(b);
                }
                catch(exception ex)
                {
                
                }
                           
            }
            return IsCredit;
        }
        set;
    }     
    
    public List<String> lstAccountIds
    {
        get{
            List<String> ids = new List<String>();
            for(Account tempApplicant: Accounts)
            {
               ids.add(tempApplicant.id);                           
            }
            return ids;
        }
    }
    
    public String AccountIds  
    {
        get
        {
            String accountIds  = '(';
            boolean firstItem = true;
            
            for(Account tempApplicant: Accounts)
            {
                if(firstItem)
                {
                    firstItem = false;
                }
                else
                {
                    accountIds  += ',';   
                }        
                accountIds  += '\'' + tempApplicant.id+ '\'';
                           
            }
            accountIds  += ')';
            return accountIds;
        }
    }
    
    public PageReference GoToNextEvent()
    {
        system.debug('Created Event ' + CreatedEvent);
        if(CreatedEvent == null)
            return null;
        
        system.debug('Redirect page ' + NextEventUrl);    
        return new PageReference(NextEventUrl);
    }
    
    public boolean CompleteEvent()
    {       
        //Check required fields
        system.debug('Checking required fields');
        if(!CheckRequriedFields())
        {
            system.debug('CheckRequriedFields - fields requried');
            return null;
        }
    
        IsCompleted =true;             
        //IBBEvents director = new IBBEvents(opp.ProductEventDirector__c);
        
        //check    
        Boolean returnValue = director.CompleteEvent(EventLog, opp);  
        if(!returnValue)return null;
                
                
        CreatedEvent = director.GetCreatedEvent(); 
        system.debug('Created Event : ' + CreatedEvent);
        system.debug('Error : ' + director.ErrorMessage());
        
        if(director.GetCreatedEventLocation() != null)
        {
            NextEventUrl  = director.GetCreatedEventLocation() + '?id=' +CreatedEvent.id;
        }
        else
        {
            NextEventUrl  = '/apex/HPPBOEvent?id=' + CreatedEvent.id;
        }
        
        
        system.debug('Director.Created Event ' + director.GetCreatedEvent());
        system.debug('Created Event ' + CreatedEvent );
        
        return returnValue; 
    }  
    
    public boolean CheckRequriedFields()
    {            
        
        if(Event.RequiredFields__c  == null)
        return true;

        system.debug('required fields value : ' + Event.RequiredFields__c);
    
        List<HPPObjects.RequiredFields> fields =  
              (List<HPPObjects.RequiredFields>)JSON.deserialize(Event.RequiredFields__c , List<HPPObjects.RequiredFields>.class);
                  
        Boolean hasError = false;       
        system.debug('fields to check : ' + fields.size())  ;         
        for(HPPObjects.RequiredFields rf : fields)
        {
            //Boolean isValid= false;
            system.debug('Checking field ' + rf.ObjectName + '.' + rf.Field);
            if(!CheckFieldRequired(rf.Field,rf.ObjectName))
            {
                String msg ;
                
                if(rf.Message!= null)
                {
                    msg = rf.Message;
                }
                else
                {
                    msg = rf.field + ' on ' + rf.objectName + ' is required' ;
                }
            
            
                ApexPages.Message myMsg;
                myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,msg );
                
                ApexPages.addMessage(myMsg );
                hasError = true;
            }
        }                 
                  
        return !hasError;
    }
    
    public boolean CheckFieldRequired(string field,string objectname)
    {
        system.debug('CheckFieldRequired: field=> ' + field + ' object=> ' + objectname);
        if(ObjectName.equalsIgnoreCase('opportunity'))
        {
            return CheckOppField(field);
        }
            
        if(ObjectName.equalsIgnoreCase('account'))
        {
            return CheckAccField(field);
        }
            
        if(ObjectName.equalsIgnoreCase('HPP_extended_opportunity__c'))
        {
            return CheckExOppField(field);
        }
        return false;
    }
    
    
    public boolean CheckOppField(String field)
    {
        system.debug('Object value of field ' +  field + ' = ' +Opp.get(field) );
        return Opp.get(field) != null;        
    }
    
    public boolean CheckAccField(String field)
    {
        system.debug('Object value of field ' +  field + ' = ' +Acc.get(field) );
        return Acc.get(field) != null;        
    }
    
    public boolean CheckExOppField(String field)
    {
        system.debug('Object value of field ' +  field + ' = ' +ExOpp.get(field) );
        return ExOpp.get(field) != null;        
    }        
    
    public List<Account> GetAccount(string id,string query )
    {
        List<SOQLQuery__c> q = SOQLQuery__c.getall().values();
        SOQLQuery__c found = null;
        
        for(SOQLQuery__c s : q)
        {
            if(s.name.equalsIgnoreCase(query))
            {
                found = s;
                break;
            }            
        }
               
        if(found == null)
            return DataHelper.GetAccount(id);
            
            
        String soql = LiabilitiesHelperFunctions.SoqlQuery(found);
        soql += ' where id = ' + id;
        return DataBase.Query(soql);
        
    }
    
    public List<Account> GetAccount(Integer applicant, string query)
    {
        return GetAccount(Accounts [applicant-1].id,query);
    }
    public List<Account> GetAccount(string query)
    {
        return GetAccount(Accounts [Curapp].id,query);
    }
    
    
    
    
    
 
}